alias peptd="cd /mnt/r/xampp/htdocs/sensiolabs/td"
alias htdocs="cd /mnt/r/xampp/htdocs/"
alias gitloggraph="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"
alias trr="tree -d -L 2"
alias trrr="tree -d -L 3"
alias symfony="cd /mnt/r/xampp/htdocs/sensiolabs/symfony/htdocs"
alias plugins="cd /mnt/r/xampp/htdocs/sensiolabs/symfony/plugins"
alias technews="cd /mnt/r/xampp/htdocs/sensiolabs/projets/TechNews"
alias projet1="cd /mnt/r/xampp/htdocs/sensiolabs/projets/pep4juneprojet1"
alias lg1="git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' --all"
alias lg2="git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset)%n''          %C(white)%s%C(reset) %C(dim white)- %an%C(reset)' --all"
