version: '3'
services:
  web:
    build: .docker
    container_name: mon-projet-dev
    labels:
      traefik.frontend.rule: "Host:host-du-projet.domain.com"
      traefik.backend: "nom-traefik-backend"
      traefik.docker.network: "mon-network"
      traefik.port: "80"
      traefik.frontend.entryPoints: "http,https"
    networks:
      - proxy
    volumes:
      - .:/data/project/
    working_dir: /data/project/
    stdin_open: true
    tty: true
    restart: always
    extra_hosts:
      host-du-projet.domain.com: 127.0.0.1
    environment:
      APP_ENV: 'dev'
      APP_SECRET: ''
      DATABASE_URL: 'mysql://user:passwd@db:3306/databasename'
      CORS_ALLOW_ORIGIN: '^https?://localhost(:[0-9]+)?$$'
  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-mon-projet-dev
    restart: always
    volumes:
      - .docker/data/db:/var/lib/mysql
    labels:
      traefik.docker.network: "proxy"
      traefik.backend: "db-mon-projet-dev"
      traefik.port: "3306"
      traefik.frontend.rule: "Host:host-du-projet.domain.com"
      traefik.frontend.entryPoints: "http, https"
    ports:
      - 3310:3306
    networks:
      - proxy
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: databasename
      MYSQL_USER: user
      MYSQL_PASSWORD: passwd

networks:
  proxy:
    external: true
